# fly.toml app configuration file generated for readx on 2023-08-29T21:57:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "readx"
primary_region = "hkg"
console_command = "/rails/bin/rails console"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
